version: '3.8'

services:
    web:
        build:
            dockerfile: docker/web.dockerfile
            target: dev
        volumes:
            - ./web:/usr/src/app
        command: npm run start:dev
        ports:
            - "8080:8080"
        environment: 
            NODE_ENV: development
            DEBUG: nodejs-docker-express:*